# Generated by Django 5.2.7 on 2025-10-03 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtiva', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tarefa', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('categoria', models.CharField(choices=[('URGENTE E IMPORTANTE', 'Urgente e Importante'), ('URGENTE NÃO IMPORTANTE', 'Urgente não importante'), ('IMPORTANTE NÃO URGENTE', 'Importante não Urgente'), ('IMPORTANTE E URGENTE', 'Importante e Urgente')], max_length=30)),
                ('estimativa_horas', models.TimeField()),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='produtiva.projeto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_atribuidas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Apontamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicial', models.TimeField(auto_now_add=True)),
                ('hora_final', models.TimeField(null=True)),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apontamentos', to='produtiva.tarefa')),
            ],
        ),
    ]
