# Generated by Django 5.2.7 on 2025-10-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtiva', '0002_tarefa_apontamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='horas_gastas',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
