# Generated by Django 5.2.7 on 2025-10-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtiva', '0003_tarefa_horas_gastas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='horas_gastas',
            field=models.TimeField(default='00:00:00', null=True),
        ),
    ]
