# Generated by Django 5.2.7 on 2025-10-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtiva', '0004_alter_tarefa_horas_gastas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='categoria',
            field=models.CharField(choices=[('IMPORTANTE E URGENTE', 'Importante e Urgente'), ('IMPORTANTE E NÃO URGENTE', 'Importante e Não Urgente'), ('URGENTE E NÃO IMPORTANTE', 'Urgente e Não Importante'), ('NÃO IMPORTANTE E NÃO URGENTE', 'Não Importante e Não Urgente')], max_length=30),
        ),
    ]
