# Generated by Django 5.2.7 on 2025-10-23 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtiva', '0005_alter_tarefa_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='horas_gastas',
        ),
        migrations.AddField(
            model_name='apontamento',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apontamentos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='apontamento',
            name='hora_final',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apontamento',
            name='hora_inicial',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='categoria',
            field=models.CharField(choices=[('URGENTE_IMPORTANTE', 'Importante e Urgente'), ('IMPORTANTE_NAO_URGENTE', 'Importante e Não Urgente'), ('URGENTE_NAO_IMPORTANTE', 'Urgente e Não Importante'), ('NAO_IMPORTANTE_NAO_URGENTE', 'Não Importante e Não Urgente')], max_length=30),
        ),
    ]
