# Generated by Django 5.2.7 on 2025-10-23 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtiva', '0006_remove_tarefa_horas_gastas_apontamento_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='estimativa_horas',
        ),
    ]
