# Generated by Django 5.2.7 on 2025-10-23 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtiva', '0007_remove_tarefa_estimativa_horas'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='estimativa_horas',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
    ]
