# Generated by Django 5.2.7 on 2025-10-23 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtiva', '0008_tarefa_estimativa_horas'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Arquivado'),
        ),
    ]
