# Generated by Django 5.2.7 on 2025-10-23 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtiva', '0009_projeto_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='is_deleted',
        ),
    ]
