# Generated by Django 5.2.7 on 2025-10-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtiva', '0010_remove_projeto_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='cancelado',
            field=models.BooleanField(default=False),
        ),
    ]
