# Generated by Django 5.2.7 on 2025-10-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtiva', '0011_projeto_cancelado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='cancelada',
            field=models.BooleanField(default=False),
        ),
    ]
