# Generated by Django 5.2.7 on 2025-11-08 21:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtiva', '0013_perfil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='participantes',
            field=models.ManyToManyField(blank=True, related_name='projetos_participando', to=settings.AUTH_USER_MODEL, verbose_name='Participantes'),
        ),
    ]
