# Generated by Django 5.2.8 on 2025-11-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtiva', '0014_projeto_participantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='concluido',
            field=models.BooleanField(default=False, verbose_name='Concluído'),
        ),
    ]
