# Generated by Django 5.2.8 on 2025-11-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtiva', '0015_projeto_concluido'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='concluida',
            field=models.BooleanField(default=False),
        ),
    ]
