# Generated by Django 5.2.4 on 2025-07-23 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_apontamento_tarefa"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apontamento",
            options={},
        ),
        migrations.AlterModelOptions(
            name="tarefa",
            options={},
        ),
        migrations.AlterField(
            model_name="tarefa",
            name="projeto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="apontamentos",
                to="usuarios.projeto",
            ),
        ),
    ]
