# Generated by Django 5.2.4 on 2025-09-30 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_apontamento_options_alter_tarefa_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='categoria',
            field=models.CharField(choices=[('URGENTE E IMPORTANTE', 'Urgente e Importante'), ('URGENTE NÃO IMPORTANTE', 'Urgente não importante'), ('IMPORTANTE NÃO URGENTE', 'Importante não Urgente'), ('IMPORTANTE E URGENTE', 'Importante e Urgente')], max_length=30),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='usuarios.projeto'),
        ),
    ]
